export const currentPageNumber: any = {
  contructors: 1,
  dailyWorker: 2,
  staffs: 3,
  tools: 4,
  materials: 5,
  pictures: 6,
  seassion: 7,
  problems: 8,
  progress: 9,
  letters: 10,
  effectiveActions: 11,
  fundsPayments: 12,
  projectsfinanceInfo: 13,
  operationLicense: 14,
};
